#! /bin/bash

module load Python
module load Babel

python LengthAngleAnalysis.py Crys1*.xyz LengthCheck.txt AngleCheck.txt 
cat out.txt


#wait

#listxyz=`ls *.inp`
#i=1
#for item in $listxyz
#do
#  ID=`printf "%0*d\n" 3 $i`
#  mv $item "q$ID.$item"
#  echo "file $i: $item --> q$ID.$item"
#  let i=i+1
#done
